name: Deploy Flask App to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flask

      - name: Build Static HTML
        run: |
          python app.py

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './build'
          name: github-pages
          retention-days: 1

      - name: Deploy to GitHub Pages
        id: deploy
        uses: actions/deploy-pages@v4
